### ISSUE TITLE
Leverage hardware acceleration where possible

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.MessagePack#105]
@pCYSl5EDgo did some amazing work over at https://github.com/MessagePack-CSharp/MessagePack-CSharp/tree/master/src/MessagePack.Experimental that is probably worth porting over to this library.

**Comment by pCYSl5EDgo** [comment]
Ok. I'll try to port it.

**Comment by AArnott** [comment]
@pCYSl5EDgo Let's go ahead and put it into the main library project rather than an "Experimentals" side project.
