### ISSUE TITLE
Incorrect deserialization of System.Drawing.Color property

### ISSUE THREAD

**Issue by fralorange** [AArnott/Nerdbank.MessagePack#168]
**Bug description**
When serializing an object containing a property of type System.Drawing.Color and then deserializing that object, the value of the Color property becomes [Empty]. It is not clear whether the problem is related to the serialization or deserialization process.

**Repro steps**
C# code to reproduce, the first test fails, but the second passes (even though Point is also a struct and from the same namespace)

```C#
[GenerateShape]
public partial record Person(string Name, System.Drawing.Color ShirtColor);

[GenerateShape]
public partial record PersonWithPosition(string Name, System.Drawing.Point Position);

public class SerializerTest
{
    [Fact]
    public void SerializeAndDeserializeObjectWithColorAsProperty_ShouldPersistDataCorrectly()
    {
        // Arrange
        var serializer = new MessagePackSerializer();
        var person = new Person("John", System.Drawing.Color.MediumPurple);

        // Act
        var data = serializer.Serialize(person);
        var deserialized = serializer.Deserialize<Person>(data);

        // Assert
        Assert.Equal(person.ShirtColor, deserialized.ShirtColor);
    }

    [Fact]
    public void SerializeAndDeserializeObjectWithPointAsProperty_ShouldPersistDataCorrectly()
    {
        // Arrange
        var serializer = new MessagePackSerializer();
        var person = new PersonWithPosition("John", new System.Drawing.Point(1,1));

        // Act
        var data = serializer.Serialize(person);
        var deserialized = serializer.Deserialize<PersonWithPosition>(data);

        // Assert
        Assert.Equal(person.Position, deserialized.Position);
    }
}
```

**Expected behavior**
The value of the Color property should be the same after deserialization as it was before serialization.

**Actual behavior**
The value of the Color property becomes [Empty] after deserialization.

- Version: 0.3.38-beta
- Target Framework: .NET 8.0
- System: Windows 10

**Additional context**
Message from first test:
Assert.Equal() Failure: Values differ
Expected: Color [MediumPurple]
Actual:   Color [Empty]

**Comment by AArnott** [comment]
Thanks for trying out and reporting what you found.
It looks like `Color` doesn't expose a public property with a setter, nor a getter with a value that can be passed to the constructor, so nothing ends up getting serialized. It's an easy fix on a case-by-base basis though, and as this is in the core BCL it seems worthwhile to make work as built-in behavior.
