### ISSUE TITLE
Provide API to reduce string allocations in user-defined custom converters

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.MessagePack#183]
See the `CommonString` struct defined in vs-streamjsonrpc (like this [one](https://github.com/microsoft/vs-streamjsonrpc/pull/1100/files#diff-4c6beea6e8b95d5ac6c4b9beff7271e38f926fcffb88f40d397af65bd1d47424)) which currently uses MessagePack-CSharp APIs. We should expose equivalent APIs from this library, and/or expose a `CommonString`-like struct so that the user doesn't have to write it.

**Comment by AArnott** [comment]
CC: @trippwill

**Comment by trippwill** [comment]
In adding support for this to vs-streamjsonrpc, we have a many instances of this pattern for CommonString like `Version2`, which would be awesome to simplify:

```csharp
        if (!reader.TryReadStringSpan(out ReadOnlySpan<byte> valueBytes))
        {
            // TODO: More specific exception type
            throw new NBMP::MessagePackSerializationException(Resources.UnexpectedErrorProcessingJsonRpc);
        }

        // Recognize "2.0" since we expect it and can avoid decoding and allocating a new string for it.
        if (Version2.TryRead(valueBytes))
        {
            return Version2.Value;
        }
```

**Comment by AArnott** [comment]
Am I reading this right? It looks bad:

```cs
  if (!reader.TryReadStringSpan(out ReadOnlySpan<byte> valueBytes))
{
  // TODO: More specific exception type
  throw new NBMP::MessagePackSerializationException(Resources.UnexpectedErrorProcessingJsonRpc);
}
```

`TryReadStringSpan` is _supposed_ to be able to return `false` when the string isn't contiguous in memory, so throwing in a perfectly legitimate (though uncommon) case seems broken.

**Comment by trippwill** [comment]
This is the code path from MessagePackFormatter. If we can't get the string as a span of bytes, there's nowhere to go:

```csharp
        ReadOnlySpan<byte> valueBytes = MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
        if (Version2.TryRead(valueBytes))
        {
            return Version2.Value;
        }
```

**Comment by AArnott** [comment]
> This is the code path from MessagePackFormatter

That one is fine, because if the string isn't contiguous, it'll allocate memory and _make_ it contiguous. It's the `if (!TryReadStringSpan)` that's buggy. 
But with the new API I'm developing in NB.MP, hopefully that code will go away anyway in favor of something simpler. So no worries about it for now.
