### ISSUE TITLE
Explore optimizing for 'stateful' custom converters

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.MessagePack#186]
The vs-streamjsonrpc pull request that adds a formatter that uses this library creates a new `MessagePackSerializer` for every JSON-RPC connection. This is required (at least) due to the requirement for custom converters that carry connection-specific state.

Rather than require new converters for every connection, what if we add a property to `MessagePackSerializationContext` that the 'app' can control (vs-streamjsonrpc in this case) that converters can downcast to get the state they need?

But then we'd need a way to let each connection provide a custom state object or custom starter `MessagePackSerializationContext` struct without the need to create a new `MessagePackSerializer`.

**Comment by AArnott** [comment]
## Design

- `SerializationContext` adds a `private readonly ImmutableDictionary<object, object>` and methods that allow addition, retrieval by key, and clearing (but not enumeration) of its content.
- `MessagePackSerializer` moves its converter cache into another object that may or may not be discarded with mutations on `MessagePackSerializer` properties based on whether they influence the cache. Most properties will have impact and thus changing them will discard the cache. But changes to the `StartingContext` property will _not_ discard the converter cache, allowing new serializers to be created with new context objects without repeating the startup hit.
- Converters will of course be allowed to retrieve data from the new state dictionary. They will also be allowed to add/change/clear it. Because the dictionary is a persistent collection, only callees from that converter invocation will notice the changes made to the state dictionary. 
- If the value added to the state dictionary is itself mutable, then the app author responsible for adding it takes on responsibility for the implications (which include thread-safety and unwanted cross-contamination between serialization jobs.)

This also opens the door to other non-discarding properties, or (ultimately) the possibility of encapsulating all the options that influence converter generation into a new options object that may cache the converters and be reused across novel MessagePackSerializer instances. But this is not in scope for this change, and possibly not even desirable.

**Comment by AArnott** [comment]
The docs for this new feature are at https://aarnott.github.io/Nerdbank.MessagePack/docs/custom-converters.html#stateful-converters.
@trippwill FYI

**Comment by trippwill** [comment]
Looks perfect for solving the connection state problem.
👌
