### ISSUE TITLE
Bring down trimmed application size

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.MessagePack#190]
The AotNativeConsole app project I recently added to the solution shows that as soon as MessagePackSerializer is used, the app .exe jumps from 1MB to 3.9MB. And it only serializes a tiny object, a List<T> and an int. Ouch.

I removed nearly everything from this list to try to cut down on the size as an experiment, as @eiriktsarpalis  called out in https://github.com/AArnott/Nerdbank.MessagePack/pull/169#discussion_r1886438095:

https://github.com/AArnott/Nerdbank.MessagePack/blob/ed14d812eccb471e4962d0f0ac1bf9ee5826c3fe/src/Nerdbank.MessagePack/StandardVisitor.cs#L24-L56

That dropped the 3.9MB exe down to 3.4MB. A nice improvement, but can we do more?

**Comment by AArnott** [comment]
Does .NET have tooling to find the API references from my library that lead to bringing in far more executable code in a trimmed app?

@eiriktsarpalis @eerhardt

**Comment by AArnott** [comment]
Converting that hard-coded list to a generic method full of type checks reduce the trimmed app size to 3.6MB (rather than the 3.4MB that removing the list entirely achieved).

**Comment by eiriktsarpalis** [comment]
> Does .NET have tooling to find the API references from my library that lead to bringing in far more executable code in a trimmed app?
> 
> @eiriktsarpalis @eerhardt

You can use [sizoscope](https://github.com/MichalStrehovsky/sizoscope) to inspect all components kept in a trimmed Native AOT app and the dependency graph that rooted them.
