### ISSUE TITLE
Add analyzer for writing MessagePackString

### ISSUE THREAD

**Issue by trippwill** [AArnott/Nerdbank.MessagePack#198]
I missed a few cases where I wasn't calling writer.WriteRaw(MyMPString.MsgPack.Span) correctly. An analyzer that would flag these could be useful and save time debugging.

**Comment by AArnott** [comment]
When you say you weren't calling it correctly, what were you doing instead (that the analyzer would look for)?

**Comment by trippwill** [comment]
There are many call patterns that continue to work but may not be the best way, such as Write(MyMPString.Value), or the more experimental Write(MyMPString.Utf8.Span), WriteRaw(MyMPString.Utf8.Span).

I actually haven't got the round trip working yet using TryRead.

One suggestion for the writer API, maybe Write() could take a MessagePackString directly?
