### ISSUE TITLE
Cannot set serializer context state using a MessagePackSerializer reference

### ISSUE THREAD

**Issue by trippwill** [AArnott/Nerdbank.MessagePack#205]
This code doesn't compile:

```csharp
serializer.StartingContext["key"] = this;
```

Results in this error:

`CS1612	Cannot modify the return value of 'MessagePackSerializer.StartingContext' because it is not a variable`

**Comment by AArnott** [comment]
This is by design. But I've created a PR to document the syntax that works.

**Comment by AArnott** [comment]
In a few moments, the docs will be updated and you'll find the example here: https://aarnott.github.io/Nerdbank.MessagePack/docs/custom-converters.html?tabs=net#stateful-converters
