### ISSUE TITLE
Duplicate Key Exception when serializing struct with PropertyShape attributes

### ISSUE THREAD

**Issue by trippwill** [AArnott/Nerdbank.MessagePack#208]
Version: CI 0.3.76-beta

I haven't found time to reduce the repro, but I thought I should go ahead and report what I saw.

For this struct:
```csharp
    [DataContract]
    internal struct MarshalToken
    {
        [MessagePack.SerializationConstructor]
#pragma warning disable SA1313 // Parameter names should begin with lower-case letter
        public MarshalToken(int __jsonrpc_marshaled, long handle, string? lifetime, int[]? optionalInterfaces)
#pragma warning restore SA1313 // Parameter names should begin with lower-case letter
        {
            this.Marshaled = __jsonrpc_marshaled;
            this.Handle = handle;
            this.Lifetime = lifetime;
            this.OptionalInterfacesCodes = optionalInterfaces;
        }

        [DataMember(Name = "__jsonrpc_marshaled", IsRequired = true)]
        [STJ.JsonPropertyName("__jsonrpc_marshaled"), STJ.JsonRequired]
        public int Marshaled { get; set; }

        [DataMember(Name = "handle", IsRequired = true)]
        [STJ.JsonPropertyName("handle"), STJ.JsonRequired]
        public long Handle { get; set; }

        [DataMember(Name = "lifetime", EmitDefaultValue = false)]
        [STJ.JsonPropertyName("lifetime"), STJ.JsonIgnore(Condition = STJ.JsonIgnoreCondition.WhenWritingNull)]
        public string? Lifetime { get; set; }

        [DataMember(Name = "optionalInterfaces", EmitDefaultValue = false)]
        [STJ.JsonPropertyName("optionalInterfaces"), STJ.JsonIgnore(Condition = STJ.JsonIgnoreCondition.WhenWritingNull)]
        public int[]? OptionalInterfacesCodes { get; set; }
    }
```

I tried applying the PropertyShape attribute to each property, using the same names as the other serialization attributes. Theses name match the ctor argument names.

I also applied the GenerateShape attribute, and made the struct partial.

When serializing using NBMP, I would get a duplicate key exception. I traced the source to NB.MP GetOrCreateConverter, on a line that produced a dictionary from the type shape's constructor params. 

The solution was to remove the PolyType attributes from the struct, and use a witness type for the struct's shape.

**Comment by AArnott** [comment]
Thanks for the report. This is something of a known issue, but not one I had a bug on or test for, so thanks for reporting.

I believe you can workaround this by renaming your constructor parameters to match the names of the properties. 

```diff
-public MarshalToken(int __jsonrpc_marshaled, long handle, string? lifetime, int[]? optionalInterfaces)
+public MarshalToken(int marshaled, long handle, string? lifetime, int[]? optionalInterfacesCodes )
```

Even after I fix the bug, I believe it'll just turn the exception type and message into another one that leads you to this same change.

**Comment by AArnott** [comment]
Given this type:

```cs
[GenerateShape]
internal partial record TypeWithConstructorParameterMatchingSerializedPropertyName
{
	public TypeWithConstructorParameterMatchingSerializedPropertyName(int otherName)
		=> this.Marshaled = otherName;

	[PropertyShape(Name = "otherName")]
	public int Marshaled { get; set; }
}
```

The constructor claims that there are *two* parameters by the same name:

```cs
private global::PolyType.Abstractions.IConstructorParameterShape[] __CreateConstructorParameters_TypeWithConstructorParameterMatchingSerializedPropertyName() => new global::PolyType.Abstractions.IConstructorParameterShape[]
{
    new global::PolyType.SourceGenModel.SourceGenConstructorParameterShape<(int, int, byte Flags), int>
    {
        Position = 0,
        Name = "otherName",
        ParameterType = Int32,
        Kind = global::PolyType.Abstractions.ConstructorParameterKind.ConstructorParameter,
        IsRequired = true,
        IsNonNullable = true,
        IsPublic = true,
        HasDefaultValue = false,
        DefaultValue = default,
        Setter = static (ref (int, int, byte Flags) state, int value) => state.Item1 = value,
        AttributeProviderFunc = static () => typeof(global::MessagePackSerializerTests.TypeWithConstructorParameterMatchingSerializedPropertyName).GetConstructor(__BindingFlags_Instance_All, null, [typeof(int)], null)?.GetParameters()[0],
    },

    new global::PolyType.SourceGenModel.SourceGenConstructorParameterShape<(int, int, byte Flags), int>
    {
        Position = 1,
        Name = "otherName",
        ParameterType = Int32,
        Kind = global::PolyType.Abstractions.ConstructorParameterKind.MemberInitializer,
        IsRequired = false,
        IsNonNullable = true,
        IsPublic = true,
        HasDefaultValue = false,
        DefaultValue = default,
        Setter = static (ref (int, int, byte Flags) state, int value) => { state.Item2 = value; state.Flags |= 1; },
        AttributeProviderFunc = static () => typeof(global::MessagePackSerializerTests.TypeWithConstructorParameterMatchingSerializedPropertyName).GetProperty("Marshaled", __BindingFlags_Instance_All, null, typeof(int), [], null),
    },
};
```

It is this `Name` collision that's causing my library to throw an exception.

If I just change the constructor parameter name to the (expected) name `marshaled`, the two parameters collapse to just one:

```cs
private global::PolyType.Abstractions.IConstructorParameterShape[] __CreateConstructorParameters_TypeWithConstructorParameterMatchingSerializedPropertyName() => new global::PolyType.Abstractions.IConstructorParameterShape[]
{
    new global::PolyType.SourceGenModel.SourceGenConstructorParameterShape<int, int>
    {
        Position = 0,
        Name = "otherName",
        ParameterType = Int32,
        Kind = global::PolyType.Abstractions.ConstructorParameterKind.ConstructorParameter,
        IsRequired = true,
        IsNonNullable = true,
        IsPublic = true,
        HasDefaultValue = false,
        DefaultValue = default,
        Setter = static (ref int state, int value) => state = value,
        AttributeProviderFunc = static () => typeof(global::MessagePackSerializerTests.TypeWithConstructorParameterMatchingSerializedPropertyName).GetConstructor(__BindingFlags_Instance_All, null, [typeof(int)], null)?.GetParameters()[0],
    },
};
```

It looks like the extra parameter shape is provided for any parameter that isn't recognized as matching a property shape. And the fact that the unrecognized parameter name happens to match the `PropertyShapeAttribute.Name` value is what causes the dictionary key collision.

I'll keep studying with this insight to find a good solution.

**Comment by AArnott** [comment]
@eiriktsarpalis  Do you have any suggestions?

**Comment by AArnott** [comment]
I think for purposes of capturing the default value (if specified), on collisions I'll just prefer the `Kind = ConstructorParameterKind.ConstructorParameter` parameter shape.

**Comment by eiriktsarpalis** [comment]
> If I just change the constructor parameter name to the (expected) name `marshaled`, the two parameters collapse to just one:

This is just following STJ semantics where parameters are joined to properties by their IL names only and not any potential custom names. This is to allow parameters automatically inherit custom names set by their corresponding properties, i.e. have the following class roundtrip with the expected contract.
```c#
public class MyPoco(int value)
{
    [JsonPropertyName("customName")]
    public int Value { get; } = value;
}
```
Assuming we changed the logic so that parameters are joined to properties by their final contract names, then the above would stop working. If we were to consider an alternative algorithm then it should at least try to preserve the above scenario but without being too unintuitive to the user about how it works.

**Comment by AArnott** [comment]
Yes, I like your default behavior as it presently is. Best for the .NET APIs (property names and parameter names) to agree and for the serialized rename to be an orthogonal thing. 
I'm just trying to figure out how to deal with the case where the constructor parameter follows a different naming convention so it doesn't throw. My PR at present turns out to allow either convention in the ctor parameter names.

**Comment by eiriktsarpalis** [comment]
> My PR at present turns out to allow either convention in the ctor parameter names.

I didn't take a look at it. Is it something that could be incorporated in PolyType proper?

**Comment by AArnott** [comment]
That's an interesting idea. It _does_ introduce cases that we may want test cases for to at least document and lock in behavior (whether broken or working). For example, classes with constructors that have _both_ a parameter with the C# property name and a parameter with the propertyshape name.
