### ISSUE TITLE
Offer camelCase property name serialization

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.MessagePack#35]
We should offer an option on individual types or on the whole serialization job to default to converting PascalCase property names to camelCase.

**Comment by AArnott** [comment]
@eiriktsarpalis In coding this up, I realize that `IPropertyShape.Name` doesn't allow me to distinguish between explicitly set properties via the `PropertyShapeAttribute.Name` vs. names that are inferred from the C# declared property name.
I'd like the policy to apply to all properties' *default* names, but not override explicitly set names. 

Do you agree with this policy? If so, how would you suggest I implement it? If not, why not?

**Comment by AArnott** [comment]
I'm just going with the AttributeProvider you expose to retrieve the attribute to see if `Name` has been explicitly set. Not a huge fan of bringing Reflection into this for every single property, but it gets me unblocked anyway.

**Comment by eiriktsarpalis** [comment]
> I'm just going with the AttributeProvider you expose to retrieve the attribute to see if `Name` has been explicitly set. Not a huge fan of bringing Reflection into this for every single property, but it gets me unblocked anyway.

The `AttributeProvider` is always `MemberInfo` for the case of the built-in providers, so perhaps it's as simple as checking `propertyShape.Name == (propertyShape.AttributeProvider as MemberInfo)?.Name`.

I'm thinking that the concept of applying a naming policy is something that transfers to shapes in general, so perhaps it makes sense to lift that to being a feature in the core library.

**Comment by eiriktsarpalis** [comment]
> I was thinking the same thing.

Could you create an issue please?
