### ISSUE TITLE
Question About Custom Converters

### ISSUE THREAD

**Issue by FireController1847** [AArnott/Nerdbank.MessagePack#71]
Let's say I have object A. I have an array of object A which is a property of a custom converter for object B. My question is, how do I utilize context.GetConverter to use the built-in converts for things like arrays?

Example:
```csharp
context.GetConverter<ArrayConverter<ObjectA>>().Serialize()
```

Since `ArrayConverter` is marked as `internal`, I don't have access to it. I may be missing the obvious answer, but I can't seem to figure it out for the life of me.

Thanks for this incredible library! It's been a breeze to use thus far.

**Comment by AArnott** [comment]
> Thanks for this incredible library! It's been a breeze to use thus far.

Wonderful. Thank you for the feedback. More features are coming. And the APIs aren't stable yet, just to warn you. The library is brand new.

I'm struggling to understand your scenario though. It sounds like you have a converter that needs to serialize an array of some type. If you were just serializing _one_ instance of another type, you could do:

```cs
context.GetConverter<TypeA>().Serialize(ref writer, value.A, context);
```

You *don't* need to include the *converter* type itself in the generic type argument. You just ask `GetConverter` for the converter necessary for whatever data type you supply.

But you actually have an *array* of `TypeA` (i.e. `TypeA[]`) that you need to serialize. Is that right? Naively then, I'd want to say this would work:

```cs
context.GetConverter<TypeA[]>().Serialize(ref writer, value.ArrayOfA, context);
```

However `TypeA[]` is a distinct type from `TypeA`, and you must guarantee a "shape" for it has been generated by the compiler. So what you'd have to do is add this attribute to a witness class (you could use your custom converter itself):

```cs
[GenerateShape<A[]>]
partial class CustomTypeConverter // ...
```

Then you would specify your witness class as a second type argument in your request for a converter:

```cs
context.GetConverter<A[], CustomTypeConverter>().Serialize(ref writer, value.ArrayOfA, context);
```

**Comment by AArnott** [comment]
I am beefing up the docs in #73 to cover the array case. It will show up at https://aarnott.github.io/Nerdbank.MessagePack/docs/custom-converters.html#delegating-to-sub-values when published in a few minutes.

**Comment by FireController1847** [comment]
I appreciate the quick response and the included documentation update! You're absolutely awesome. I've been watching the MessagePack library for a bit and it genuinely interests me and when I saw your reply to https://github.com/MessagePack-CSharp/MessagePack-CSharp/pull/1998 I knew I had to check it out immediately haha. I'm totally cool with it being early API and whatnot; it gives me an opportunity to be a beta tester :grin:

In regards to my situation, I've managed to make a working solution to help better describe my issue.

What I was moreso considering was, at the current moment if I want to write a custom converter, I need to essentially rewrite the code found in the `ArrayConverter` for an array type myself. For example, I have a class which contains a `ConcurrentDictionary<uint, MyStruct>`. The `uint` (the key) in this instance, is simply a value that's a part of `MyStruct` (let's call it `MyStruct.Id` for simplicity sake). I'm writing a custom converter to serialize this concurrent dictionary where I have to fetch the array like so: `value.MyDictionary.Values.ToArray()`. Everything following this point is now duplicated code:
```csharp
MyStruct[] array = value.MyDictionary.Values.ToArray();
context.DepthStep();
writer.WriteArrayHeader(array.Length);
for (int i = 0; i < array.Length; i++) {
    context.GetConverter<MyStruct>().Serialize(ref writer, ref array[i], context);
}
```
Albeit, it's not _nearly_ a lot of duplicated code now that I look at it haha. And as I'm realizing the true power and flexibility of making a custom serializer, I absolutely love what you've managed to create here. Still, it would be nice to be able to do something of this sorts:
```csharp
MyStruct[] array = value.MyDictionary.Values.ToArray();
context.GetConverter<MyStruct[]>().Serialize(ref writer, ref array, context);
```
or
```csharp
MyStruct[] array = value.MyDictionary.Values.ToArray();
context.GetConverter<ArrayConverter<MyStruct>>().Serialize(ref writer, ref array, context);
```
Admittedly, this seems to be what you had just added to the documentation about generating a shape for `MyStruct[]` itself, so that may be a viable solution in this instance. I've just tried that now as of writing this, but I still get the issue of the converter complaining about `MyStruct[]` not being a valid `IShapeable<MyStruct[]>` with the exception "There is no implicit reference" to that type.

Hopefully I worded that well haha. I'm trying to provide as much information as possible to help describe the issue.

**Comment by AArnott** [comment]
> but I still get the issue of the converter complaining about MyStruct[] not being a valid IShapeable<MyStruct[]> with the exception "There is no implicit reference" to that type:

It sounds like you're missing this bit:

```diff
-context.GetConverter<A[]>().Serialize(ref writer, ref array, context);
+context.GetConverter<A[], ExampleConverter>().Serialize(ref writer, ref array, context);
```

**Comment by FireController1847** [comment]
Seems I still have the issue. This is the impl code; "MyStruct" being "CachedSong" (the containing class being SongCache)

```csharp
/// <summary>
/// Provides serialization and deserialization for <see cref="SongCache"/>.
/// </summary>
[GenerateShape<CachedSong[]>]
public class SongCacheConverter : MessagePackConverter<SongCache> {

    /// <inheritdoc/>
    public override void Serialize(ref MessagePackWriter writer, ref SongCache? value, SerializationContext context) {
        if (value is null) {
            writer.WriteNil();
            return;
        }

        // Write like an array
        CachedSong[] array = value.Songs.Values.ToArray();
        context.DepthStep();
        writer.WriteArrayHeader(array.Length);
        for (int i = 0; i < array.Length; i++) {
            // it won't accept this
            context.GetConverter<CachedSong[], SongCacheConverter>().Serialize(ref writer, ref array, context);
        }
    }

    /// <inheritdoc/>
    public override SongCache? Deserialize(ref MessagePackReader reader, SerializationContext context) {
        if (reader.TryReadNil()) {
            return null;
        }

        // Read like an array
        context.DepthStep();
        int count = reader.ReadArrayHeader();
        CachedSong[] array = new CachedSong[count];
        for (int i = 0; i < count; i++) {
            array[i] = context.GetConverter<CachedSong>().Deserialize(ref reader, context);
        }

        // Make a new song cache and return it
        SongCache cache = new();
        foreach (CachedSong song in array) {
            cache.Songs.TryAdd(song.Song.Hash, song);
        }
        return cache;
    }
    ```

**Comment by AArnott** [comment]
```diff
 [GenerateShape<CachedSong[]>]
-public class SongCacheConverter : MessagePackConverter<SongCache> {
+public partial class SongCacheConverter : MessagePackConverter<SongCache> {
```

**Comment by AArnott** [comment]
#74 fixes the missing modifier in the docs.

**Comment by FireController1847** [comment]
Hahaha, I must be getting tired, that's such a simple thing to overlook (I knew it had to be partial haha). It works great! Thanks a ton for helping me out. Keep up the great work 🙂❤️ 

```csharp
/// <summary>
/// Provides serialization and deserialization for <see cref="SongCache"/>.
/// </summary>
[GenerateShape<CachedSong[]>]
public partial class SongCacheConverter : MessagePackConverter<SongCache> {

    /// <inheritdoc/>
    public override void Serialize(ref MessagePackWriter writer, ref SongCache? value, SerializationContext context) {
        if (value is null) {
            writer.WriteNil();
            return;
        }

        // Write like an array
        CachedSong[]? array = value.Songs.Values.ToArray();
        context.GetConverter<CachedSong[], SongCacheConverter>().Serialize(ref writer, ref array, context);
    }

    /// <inheritdoc/>
    public override SongCache? Deserialize(ref MessagePackReader reader, SerializationContext context) {
        if (reader.TryReadNil()) {
            return null;
        }

        // Read like an array
        CachedSong[]? array = context.GetConverter<CachedSong[], SongCacheConverter>().Deserialize(ref reader, context);

        // Make SongCache
        SongCache cache = new();
        if (array != null) {
            foreach (CachedSong song in array) {
                cache.Songs.TryAdd(song.Song.Hash, song);
            }
        }
        return cache;
    }

}
```
